# Practice 1

## Instructions

You're going to practice working in pandas. 


You'll walk through instantiating a `DataFrame`, reading data into it, looking at and examining that data, and then playing with it. 


A dataset on the [quality of red wines](https://archive.ics.uci.edu/ml/datasets/wine+quality) is used for this purpose.
It is located in the `data` folder within this directory. It's called `winequality-red.csv`. 


Typically, we use Jupyter notebooks like this for a very specific set of things - presentations and EDA. 


Today, as we'll be playing around with `pandas`, much of what we'll be doing is considered EDA. Therefore, by using a notebook, we'll get a tighter feedback loop with our work than we would trying to write a script. But, in general, **we do not use Jupyter notebooks for development**. 

Below, we've put a set of questions and then a cell for you to work on answers. However, feel free to add additional cells if you'd like. Often it will make sense to use more than one cell for your answers.

## Assignment Questions

### Part 1 - The Basics of DataFrames

Let's start off by following the general workflow that we use when moving data into a DataFrame: 

    * Importing pandas
    * Reading data into the DataFrame
    * Getting a general sense of the data

So, in terms of what you should do for this part...

1. Import pandas

In [1]:
import pandas as pd

2. Read the wine data into a DataFrame.

In [3]:
df_red = pd.read_csv("./data/winequality-red.csv", sep=";")
df_white = pd.read_csv("./data/winequality-white.csv", sep=";")
df = pd.concat([df_red, df_white])
df.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

3. Use the `attributes` and `methods` available on DataFrames to answer the following questions: 
    * How many rows and columns are in the DataFrame?
    * What data type is in each column?
    * Are all of the variables continuous, or are any categorical?
    * How many non-null values are in each column?
    * What are the min, mean, max, median for all numeric columns?

In [20]:
print(f"{df.shape[0]} rows, {df.shape[1]} cols\n")
print(f"Data types are:\n {df.dtypes}\nAll variables are continuous.\n")

6497 rows, 12 cols

Data types are:
 fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object
All variables are continuous.

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6497 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 659.9 KB

In [22]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000
mean,7.215307,0.339666,0.318633,5.443235,0.056034,30.525319,115.744574,0.994697,3.218501,0.531268,10.491801,5.818378
std,1.296434,0.164636,0.145318,4.757804,0.035034,17.749400,56.521855,0.002999,0.160787,0.148806,1.192712,0.873255
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992340,3.110000,0.430000,9.500000,5.000000
50%,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,6.000000
75%,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.996990,3.320000,0.600000,11.300000,6.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000

### Part 2 - Practice with Grabbing Data

Let's now get some practice with grabbing certain parts of the data. If you'd like some extra practice, try answering each of the questions in more than one way (because remember, we can often grab our data in a couple of different ways).

1. Grab the first 10 rows of the `chlorides` column.

In [27]:
df.iloc[:10][["chlorides"]]

   chlorides
0      0.076
1      0.098
2      0.092
3      0.075
4      0.076
5      0.075
6      0.069
7      0.065
8      0.073
9      0.071

2. Grab the last 10 rows of the `chlorides` column.

In [31]:
df.iloc[-10:][["chlorides"]]

      chlorides
4888      0.052
4889      0.030
4890      0.036
4891      0.038
4892      0.032
4893      0.039
4894      0.047
4895      0.041
4896      0.022
4897      0.020

3. Grab indices 264-282 of the `chlorides` **and** `density` columns.

In [32]:
df.iloc[264:283][["chlorides", "density"]]

     chlorides  density
264      0.064  0.99990
265      0.071  0.99680
266      0.096  1.00025
267      0.078  0.99730
268      0.077  0.99870
269      0.104  0.99960
270      0.087  0.99650
271      0.104  0.99960
272      0.071  0.99935
273      0.076  0.99735
274      0.088  0.99915
275      0.087  0.99650
276      0.077  0.99870
277      0.104  0.99960
278      0.073  0.99760
279      0.087  0.99910
280      0.071  0.99860
281      0.358  0.99720
282      0.067  0.99710

4. Grab all rows where the `chlorides` value is less than 0.10.

In [40]:
df[df["chlorides"] < .1]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

5. Now grab all the rows where the `chlorides` value is greater than the column's mean (try **not** to use a hard-coded value for the mean, but instead a method).

In [41]:
m = df["chlorides"].mean()
print(f"Mean chlorides: {m:.2f}")
df[df["chlorides"] > m]

Mean chlorides: 0.06

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.400000,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.800000,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.800000,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.800000,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.400000,5
...,...,...,...,...,...,...,...,...,...,...,...,...
4836,6.7,0.50,0.36,11.5,0.096,18.0,92.0,0.99642,3.11,0.49,9.600000,5
4845,6.6,0.38,0.29,2.4,0.136,15.0,93.0,0.99336,3.18,0.60,9.500000,5
4855,7.1,0.23,0.39,13.7,0.058,26.0,172.0,0.99755,2.90,0.46,9.000000,6
4856,7.1,0.23,0.39,13.7,0.058,26.0,172.0,0.99755,2.90,0.46,9.000000,6
4864,6.0,0.41,0.23,1.1,0.066,22.0,148.0,0.99266,3.30,0.47,9.633333,5

6. Grab all those rows where the `pH` is greater than 3.0 and less than 3.5.

In [43]:
# df[(df["pH"] > 3) & (df["pH"] < 3.5)]
df.query("pH > 3 and pH < 3.5")

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...
4892,6.5,0.23,0.38,1.3,0.032,29.0,112.0,0.99298,3.29,0.54,9.7,5
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6


7. Further filter the results from 6 to grab only those rows that have a `residual sugar` less than 2.0.

In [46]:
df1 = df.query("pH > 3 and pH < 3.5")
df1[df1["residual sugar"] < 2]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7
10,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.99590,3.28,0.54,9.2,5
13,7.8,0.61,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
4891,5.7,0.21,0.32,0.9,0.038,38.0,121.0,0.99074,3.24,0.46,10.6,6
4892,6.5,0.23,0.38,1.3,0.032,29.0,112.0,0.99298,3.29,0.54,9.7,5
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

### Part 3 - More Practice

Let's move on to some more complicated things. Use your knowledge of `groupby`s, `sorting` to answer the following.

1. Get the average amount of `chlorides` for each `quality` value.

In [ ]:
# Filter before aggregation should yield performance gains
df[["quality", "chlorides"]].groupby("quality").mean()

         chlorides
quality
3         0.077033
4         0.060056
5         0.064666
6         0.054157
7         0.045272
8         0.041124
9         0.027400

 2. For observations with a `pH` greater than 3.0 and less than 4.0, find the average `alcohol` value by `pH`.

In [48]:
df[["pH", "alcohol"]]\
    .query("pH > 3 and pH < 3.5")\
    .groupby("pH")\
    .mean()

        alcohol
pH
3.01  10.548148
3.02  10.351316
3.03  10.502381
3.04  10.403894
3.05  10.342955
3.06  10.318400
3.07  10.338519
3.08  10.212245
3.09  10.232039
3.10  10.314719
3.11  10.377160
3.12  10.223290
3.13  10.482692
3.14  10.163212
3.15  10.485392
3.16  10.325833
3.17  10.370199
3.18  10.500198
3.19  10.524314
3.20  10.422330
3.21  10.479517
3.22  10.612973
3.23  10.560338
3.24  10.597930
3.25  10.708095
3.26  10.691723
3.27  10.615447
3.28  10.518734
3.29  10.601953
3.30  10.428222
3.31  10.694633
3.32  10.707888
3.33  10.868411
3.34  10.283607
3.35  10.715326
3.36  10.701799
3.37  10.479651
3.38  10.753774
3.39  10.623295
3.40  10.588596
3.41  10.884375
3.42  10.490123
3.43  10.402703
3.44  10.580645
3.45  10.589189
3.46  10.698000
3.47  10.234127
3.48  10.497500
3.49  10.566667

3. For observations with an `alcohol` value between 9.25 and 9.5, find the highest amount of `residual sugar`.

In [53]:
df[["alcohol", "residual sugar"]]\
    .query("alcohol >= 9.25 and alcohol <= 9.5")\
    .max()["residual sugar"]

np.float64(19.95)

4. Create a new column, called `total_acidity`, that is the sum of `fixed acidity` and `volatile acidity`.

In [54]:
df1 = df.copy()
df1["total_acidity"] = df1["fixed acidity"] + df1["volatile acidity"]
df1[["fixed acidity", "volatile acidity", "total_acidity"]].head(5)

   fixed acidity  volatile acidity  total_acidity
0            7.4              0.70           8.10
1            7.8              0.88           8.68
2            7.8              0.76           8.56
3           11.2              0.28          11.48
4            7.4              0.70           8.10

5. Find the average `total_acidity` for each of the `quality` values.

In [56]:
df1.groupby("quality").mean()["total_acidity"]

quality
3    8.370333
4    7.746852
5    7.716415
6    7.491120
7    7.417762
8    7.126244
9    7.718000
Name: total_acidity, dtype: float64

6. Find the top 5 `density` values.

In [59]:
df.sort_values("density", axis=0, ascending=False).iloc[:5]["density"]

2781    1.03898
1663    1.01030
1653    1.01030
1435    1.00369
1434    1.00369
Name: density, dtype: float64

7. Find the 10 lowest `sulphates` values.

In [62]:
df.sort_values("sulphates", axis=0, ascending=True).iloc[:10]["sulphates"]

3244    0.22
3284    0.23
1283    0.25
1126    0.25
1210    0.25
3528    0.25
2055    0.26
4737    0.26
3476    0.26
3484    0.26
Name: sulphates, dtype: float64